#
# BoardConfig for FreeYond M5A (Unisoc UMS9230 / T606)
# Forked from cooked71 device_RE58C2 (working)
#
# SPDX-License-Identifier: Apache-2.0
#

DEVICE_PATH := device/freeyond/M5A

# Build system flags
BUILD_BROKEN_ELF_PREBUILT_PRODUCT_COPY_FILES := true
BUILD_BROKEN_DUP_RULES := true
BUILD_BROKEN_MISSING_REQUIRED_MODULES := true
BUILD_BROKEN_MISSING_KERNEL_HEADERS := true
BUILD_BROKEN_INITRC_CHECKS := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a75

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a55

# Platform
TARGET_BOARD_PLATFORM := ums9230
TARGET_BOOTLOADER_BOARD_NAME := ums9230_1h10
TARGET_NO_BOOTLOADER := true
TARGET_OTA_ASSERT_DEVICE := M5A

# Display
TARGET_SCREEN_DENSITY := 320

# GPU
TARGET_GPU_PLATFORM := mali-g52
TARGET_GPU_VARIANT := mali-g52
BOARD_USES_UNISOC_GRAPHICS := true
TARGET_USES_UNISOC_GRAPHICS := true
TARGET_USES_OPENGLES := true

# A/B (Virtual A/B)
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS += \
    boot \
    vendor_boot \
    init_boot \
    dtbo \
    system \
    system_ext \
    product \
    vendor \
    odm \
    vendor_dlkm \
    vbmeta \
    vbmeta_system \
    vbmeta_vendor \
    vbmeta_odm \
    vbmeta_product \
    vbmeta_system_ext

# Boot image
BOARD_BOOT_HEADER_VERSION := 4
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOT_HEADER_VERSION)
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_USES_VENDOR_BOOT_IMAGE := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
TARGET_NO_RECOVERY := false
BOARD_RAMDISK_USE_LZ4 := true

BOARD_KERNEL_SEPARATED_DTBO := true
BOARD_INCLUDE_DTB_IN_BOOTIMG := true

BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x05400000
BOARD_TAGS_OFFSET := 0x00000100
BOARD_DTB_OFFSET := 0x01f00000

BOARD_KERNEL_CMDLINE := console=ttyS1,115200n8 buildvariant=user
    androidboot.hardware=ums9230_1h10 \
    androidboot.dtbo_idx=1 \
    androidboot.selinux=permissive \
    loop.max_part=7 \
    swiotlb=1
BOARD_VENDOR_CMDLINE := console=ttyS1,115200n8

# Kernel (prebuilt for bring-up)
TARGET_FORCE_PREBUILT_KERNEL := true
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilts/kernel
TARGET_PREBUILT_DTB := $(DEVICE_PATH)/prebuilts/dtb.img
TARGET_PREBUILT_DTBO := $(DEVICE_PATH)/prebuilts/dtbo.img
BOARD_PREBUILT_DTBIMAGE := $(TARGET_PREBUILT_DTB)
BOARD_PREBUILT_DTBOIMAGE := $(TARGET_PREBUILT_DTBO)
PRODUCT_COPY_FILES += $(TARGET_PREBUILT_KERNEL):kernel

TARGET_KERNEL_SOURCE := kernel/freeyond/M5A
TARGET_KERNEL_CONFIG := unisoc_defconfig
TARGET_KERNEL_CLANG_VERSION := r416183b
TARGET_KERNEL_CLANG_COMPILE := true

# Partition sizes (bytes), from the M5A
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 104857600
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 262144

# Dynamic partitions
BOARD_SUPER_PARTITION_SIZE := 5872025600
BOARD_SUPER_PARTITION_GROUPS := group_unisoc
BOARD_GROUP_UNISOC_SIZE := 5867831296
BOARD_GROUP_UNISOC_PARTITION_LIST := system system_ext product vendor odm vendor_dlkm

BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2147483648
BOARD_SYSTEM_EXTIMAGE_PARTITION_SIZE := 671088640
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 1073741824
BOARD_VENDORIMAGE_PARTITION_SIZE := 805306368
BOARD_ODMIMAGE_PARTITION_SIZE := 402653184
BOARD_VENDOR_DLKMIMAGE_PARTITION_SIZE := 33554432

BOARD_BUILD_SUPER_IMAGE_BY_DEFAULT := true
BOARD_SUPER_IMAGE_IN_UPDATE_PACKAGE := true

# Filesystems (match stock fstab.ums9230_1h10)
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEM_EXTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := erofs
BOARD_VENDOR_DLKMIMAGE_FILE_SYSTEM_TYPE := erofs
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

TARGET_COPY_OUT_SYSTEM_EXT := system_ext
TARGET_COPY_OUT_PRODUCT := product
TARGET_COPY_OUT_VENDOR := vendor
TARGET_COPY_OUT_ODM := odm
TARGET_COPY_OUT_VENDOR_DLKM := vendor_dlkm

BOARD_USES_METADATA_PARTITION := true

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recoveryx/recovery/etc/recovery.fstab
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# AVB
BOARD_AVB_ENABLE := true
BOARD_AVB_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_ALGORITHM := SHA256_RSA4096
BOARD_AVB_ROLLBACK_INDEX := 0
BOARD_AVB_ROLLBACK_INDEX_LOCATION := 1
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --set_hashtree_disabled_flag
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3

BOARD_AVB_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_BOOT_ROLLBACK_INDEX := 0
BOARD_AVB_BOOT_ROLLBACK_INDEX_LOCATION := 2

BOARD_AVB_VENDOR_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VENDOR_BOOT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX := 0
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX_LOCATION := 3

# Per-partition vbmeta chain (matches stock fstab)
# vbmeta_system: system + system_ext
BOARD_AVB_VBMETA_SYSTEM := system system_ext
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 4

# vbmeta_vendor: vendor
BOARD_AVB_VBMETA_VENDOR := vendor
BOARD_AVB_VBMETA_VENDOR_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_VENDOR_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_VENDOR_ROLLBACK_INDEX_LOCATION := 5

# vbmeta_odm, vbmeta_product, vbmeta_system_ext (holds vendor_dlkm on stock)
BOARD_AVB_VBMETA_CUSTOM_PARTITIONS := odm product system_ext
BOARD_AVB_VBMETA_ODM := odm
BOARD_AVB_VBMETA_ODM_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_ODM_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_ODM_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_ODM_ROLLBACK_INDEX_LOCATION := 6
BOARD_AVB_VBMETA_PRODUCT := product
BOARD_AVB_VBMETA_PRODUCT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_PRODUCT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_PRODUCT_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_PRODUCT_ROLLBACK_INDEX_LOCATION := 7
BOARD_AVB_VBMETA_SYSTEM_EXT := vendor_dlkm
BOARD_AVB_VBMETA_SYSTEM_EXT_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
BOARD_AVB_VBMETA_SYSTEM_EXT_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_SYSTEM_EXT_ROLLBACK_INDEX := 0
BOARD_AVB_VBMETA_SYSTEM_EXT_ROLLBACK_INDEX_LOCATION := 8

# VINTF: enforcement left ON. Kernel must have CONFIG_SYSVIPC unset to match
# the M5A vendor compatibility matrix.
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE += \
    vendor/freeyond/M5A/proprietary/product/etc/vintf/compatibility_matrix.xml

TARGET_FLATTEN_APEX := false

# Security
TARGET_USES_TRUSTY := true
BOARD_USES_KEYMASTER_4 := true
TARGET_KEYMINT_VERSION := 2.0

# RIL
BOARD_PROVIDES_RILD := true
ENABLE_VENDOR_RIL_SERVICE := true

# SELinux (bring-up only, remove once booting)
BOARD_SEPOLICY_VERS := 33.0
BOARD_VENDOR_SEPOLICY_DIRS += $(DEVICE_PATH)/sepolicy/vendor
SELINUX_IGNORE_NEVERALLOWS := true

# Vold
TARGET_PROVIDES_VOLD := true

# Properties
TARGET_SYSTEM_PROP += $(DEVICE_PATH)/system.prop
TARGET_VENDOR_PROP += $(DEVICE_PATH)/vendor.prop
TARGET_PRODUCT_PROP += $(DEVICE_PATH)/product.prop
TARGET_SYSTEM_EXT_PROP += $(DEVICE_PATH)/system_ext.prop
TARGET_ODM_PROP += $(DEVICE_PATH)/odm.prop
TARGET_VENDOR_DLKM_PROP += $(DEVICE_PATH)/vendor_dlkm.prop

# Vendor blobs
-include vendor/freeyond/M5A/BoardConfigVendor.mk

VENDOR_SECURITY_PATCH := 2023-06-05
